name: mosse_tracker
channels:
  - pytorch
  - defaults
  - anaconda
dependencies:
  - python=3.6
  - cudatoolkit=10.2
  - cudnn=7.6.5
  - pytorch=1.8.0
  - torchvision=0.9.0
  - pip
  - pip:
      - -r requirements.txt

      # environment tools
      - black
      - isort
      - mypy
